services:
    hsrb_pick_and_place:
        container_name: hsrb_pick_and_place
        privileged: true
        build:
            context: ..
            dockerfile: docker/Dockerfile   # added
        image: hsrb_pick_and_place:latest
        network_mode: host
        runtime: nvidia
        environment:
            - DISPLAY=$DISPLAY
            - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
            - CYCLONEDDS_URI=/home/hsrb/ros2_ws/docker/cyclonedds_profile.xml
            - ROS_DOMAIN_ID=172
            - GZ_SIM_RESOURCE_PATH=/workdir/src/hsrb_pnp_pkgs/hsrb_pick_and_place/models
            - GZ_SIM_SYSTEM_PLUGIN_PATH=/workdir/install/hsrb_gz_ros2_control/lib
        volumes:
            - ../:/home/hsrb/ros2_ws
            - /tmp/.X11-unix:/tmp/.X11-unix
        devices:
            - "/dev/video0:/dev/video0"
        working_dir: /home/hsrb/ros2_ws
        tty: true
        command: bash
